export enum CanDoDomainError {
  GLOBAL_DESCRIPTOR_REQUIRES_NO_SCHOOL = 'GLOBAL_DESCRIPTOR_REQUIRES_NO_SCHOOL',
  SCHOOL_DESCRIPTOR_REQUIRES_SCHOOL    = 'SCHOOL_DESCRIPTOR_REQUIRES_SCHOOL',
  DESCRIPTOR_ALREADY_DELETED           = 'DESCRIPTOR_ALREADY_DELETED',
  LOCALIZATION_NOT_FOUND               = 'LOCALIZATION_NOT_FOUND',
}
