export enum ContentRelationDomainError {
  SOURCE_EQUALS_TARGET = 'SOURCE_EQUALS_TARGET',
  RELATION_ALREADY_EXISTS = 'RELATION_ALREADY_EXISTS',
  SOURCE_NOT_FOUND = 'SOURCE_NOT_FOUND',
  TARGET_NOT_FOUND = 'TARGET_NOT_FOUND',
}
