import type { AttemptModel } from '../../../../../generated/prisma/models/Attempt.js';
import { Attempt } from '../../domain/entities/attempt.entity.js';
import type {
  AttemptStatus,
  CheckMode,
  DifficultyLevel,
  ExercisePathSnapshot,
  PracticedAtom,
  ReviewDecision,
} from '../../domain/entities/attempt.entity.js';

export class AttemptMapper {
  static toDomain(row: AttemptModel): Attempt {
    return Attempt.reconstitute({
      id: row.id,
      userId: row.userId,
      exerciseId: row.exerciseId,
      assignmentId: row.assignmentId,
      enrollmentId: row.enrollmentId,
      templateCode: row.templateCode,
      targetLanguage: row.targetLanguage,
      difficultyLevel: row.difficultyLevel as DifficultyLevel,
      checkMode: row.checkMode as CheckMode,
      practicedAtoms: (row.practicedAtoms as PracticedAtom[] | null) ?? [],
      status: row.status as AttemptStatus,
      score: row.score,
      passed: row.passed,
      timeSpentSeconds: row.timeSpentSeconds,
      submittedAnswer: row.submittedAnswer,
      validationDetails: row.validationDetails,
      feedback: row.feedback,
      answerHash: row.answerHash,
      revisionCount: row.revisionCount,
      answersRevealed: row.answersRevealed,
      selfChecksUsed: row.selfChecksUsed,
      startedAt: row.startedAt,
      submittedAt: row.submittedAt,
      scoredAt: row.scoredAt,
      reviewedByUserId: row.reviewedByUserId,
      reviewedAt: row.reviewedAt,
      reviewComment: row.reviewComment,
      reviewDecisions: (row.reviewDecisions as ReviewDecision[] | null) ?? null,
      schoolId: row.schoolId,
      containerId: row.containerId,
      groupId: row.groupId,
      exercisePath: row.exercisePath as ExercisePathSnapshot | null,
      reviewClaimedBy: row.reviewClaimedBy,
      reviewClaimedAt: row.reviewClaimedAt,
      previousAttemptId: row.previousAttemptId,
      autoPassedItems: row.autoPassedItems,
      totalItems: row.totalItems,
    });
  }

  static toPersistence(attempt: Attempt): AttemptModel {
    return {
      id: attempt.id,
      userId: attempt.userId,
      exerciseId: attempt.exerciseId,
      assignmentId: attempt.assignmentId,
      enrollmentId: attempt.enrollmentId,
      templateCode: attempt.templateCode,
      targetLanguage: attempt.targetLanguage,
      difficultyLevel: attempt.difficultyLevel as AttemptModel['difficultyLevel'],
      checkMode: attempt.checkMode as AttemptModel['checkMode'],
      practicedAtoms: attempt.practicedAtoms as unknown as AttemptModel['practicedAtoms'],
      status: attempt.status as AttemptModel['status'],
      score: attempt.scoreValue,
      passed: attempt.passed,
      timeSpentSeconds: attempt.timeSpentSeconds,
      submittedAnswer: attempt.submittedAnswer ?? null,
      validationDetails: attempt.validationDetails ?? null,
      feedback: attempt.feedback ?? null,
      answerHash: attempt.answerHash,
      revisionCount: attempt.revisionCount,
      answersRevealed: attempt.answersRevealed,
      selfChecksUsed: attempt.selfChecksUsed,
      startedAt: attempt.startedAt,
      submittedAt: attempt.submittedAt,
      scoredAt: attempt.scoredAt,
      reviewedByUserId: attempt.reviewedByUserId,
      reviewedAt: attempt.reviewedAt,
      reviewComment: attempt.reviewComment,
      reviewDecisions:
        attempt.reviewDecisions as unknown as AttemptModel['reviewDecisions'],
      schoolId: attempt.schoolId,
      containerId: attempt.containerId,
      groupId: attempt.groupId,
      exercisePath: attempt.exercisePath as unknown as AttemptModel['exercisePath'],
      reviewClaimedBy: attempt.reviewClaimedBy,
      reviewClaimedAt: attempt.reviewClaimedAt,
      previousAttemptId: attempt.previousAttemptId,
      autoPassedItems: attempt.autoPassedItems,
      totalItems: attempt.totalItems,
    };
  }
}
