export enum MediaAssetDomainError {
  MIME_TYPE_NOT_ALLOWED = 'MIME_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_STORAGE_KEY = 'INVALID_STORAGE_KEY',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  ASSET_ALREADY_DELETED = 'ASSET_ALREADY_DELETED',
  NOT_OWNED_BY_USER = 'NOT_OWNED_BY_USER',
  UPLOAD_NOT_CONFIRMED = 'UPLOAD_NOT_CONFIRMED',
  // Recordings (`submission_recording`, plan 70)
  RECORDING_ATTEMPT_REQUIRED = 'RECORDING_ATTEMPT_REQUIRED',
  RECORDING_TOO_LARGE = 'RECORDING_TOO_LARGE',
  RECORDING_TOO_LONG = 'RECORDING_TOO_LONG',
  RECORDING_UNREADABLE = 'RECORDING_UNREADABLE',
}
