export enum MediaAssetDomainError {
  MIME_TYPE_NOT_ALLOWED = 'MIME_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_STORAGE_KEY = 'INVALID_STORAGE_KEY',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  ASSET_ALREADY_DELETED = 'ASSET_ALREADY_DELETED',
  NOT_OWNED_BY_USER = 'NOT_OWNED_BY_USER',
  UPLOAD_NOT_CONFIRMED = 'UPLOAD_NOT_CONFIRMED',
}
