export enum GrammarRuleDomainError {
  GRAMMAR_RULE_NOT_FOUND = 'GRAMMAR_RULE_NOT_FOUND',
  EXPLANATION_NOT_FOUND = 'EXPLANATION_NOT_FOUND',
  POOL_ENTRY_NOT_FOUND = 'POOL_ENTRY_NOT_FOUND',
  INVALID_VISIBILITY_FOR_OWNER_TYPE = 'INVALID_VISIBILITY_FOR_OWNER_TYPE',
  INVALID_LEVEL_RANGE = 'INVALID_LEVEL_RANGE',
  EMPTY_BODY_MARKDOWN = 'EMPTY_BODY_MARKDOWN',
  EXPLANATION_ALREADY_PUBLISHED = 'EXPLANATION_ALREADY_PUBLISHED',
  EXPLANATION_NOT_IN_DRAFT_STATUS = 'EXPLANATION_NOT_IN_DRAFT_STATUS',
  DUPLICATE_EXPLANATION = 'DUPLICATE_EXPLANATION',
  EXERCISE_ALREADY_IN_POOL = 'EXERCISE_ALREADY_IN_POOL',
  EXERCISE_NOT_FOUND_FOR_POOL = 'EXERCISE_NOT_FOUND_FOR_POOL',
  // Adding a soft-deleted exercise to a pool is blocked. Existing pool entries
  // that reference a later-deleted exercise remain; the random-exercise endpoint
  // and pool view silently skip them.
  EXERCISE_DELETED_FOR_POOL = 'EXERCISE_DELETED_FOR_POOL',
  INVALID_WEIGHT = 'INVALID_WEIGHT',
  NO_EXERCISES_AVAILABLE = 'NO_EXERCISES_AVAILABLE',
  RULE_HAS_PUBLISHED_CONTAINER_REFERENCES = 'RULE_HAS_PUBLISHED_CONTAINER_REFERENCES',
  RULE_ALREADY_DELETED = 'RULE_ALREADY_DELETED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  SLUG_ALREADY_EXISTS = 'SLUG_ALREADY_EXISTS',
  SLUG_ALREADY_ASSIGNED = 'SLUG_ALREADY_ASSIGNED',
  INVALID_REORDER_INPUT = 'INVALID_REORDER_INPUT',
  EMPTY_TITLE = 'EMPTY_TITLE',
}
