export enum ExerciseTemplateDomainError {
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_NOT_ACTIVE = 'TEMPLATE_NOT_ACTIVE',
  LANGUAGE_NOT_SUPPORTED_BY_TEMPLATE = 'LANGUAGE_NOT_SUPPORTED_BY_TEMPLATE',
}
