export enum TagDomainError {
  INVALID_SLUG = 'INVALID_SLUG',
  TAG_ALREADY_DELETED = 'TAG_ALREADY_DELETED',
  GLOBAL_TAG_REQUIRES_NO_SCHOOL = 'GLOBAL_TAG_REQUIRES_NO_SCHOOL',
  SCHOOL_TAG_REQUIRES_SCHOOL = 'SCHOOL_TAG_REQUIRES_SCHOOL',
  SCHOOL_MISMATCH = 'SCHOOL_MISMATCH',
}
